version: "3.8"
services:
  langflow:
    image: langflow-ai/langflow:latest
    container_name: langflow
    restart: unless-stopped
    ports:
      - "7860:7860"
    environment:
      - PORT=7860
      - LANGFLOW_DATABASE_URL=sqlite:///langflow.db
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
