version: '3.8'

services:
  langflow:
    build:
      context: .                              # Raiz onde está seu Dockerfile
      dockerfile: docker_example/Dockerfile  
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      - LANGFLOW_CONFIG_DIR=app/langflow
      - GOOGLE_APPLICATION_CREDENTIALS=/keys/chatrag-3bf34-61db4767441b.json

    volumes:
      - langflow-data:/app/langflow
      - /root/chatrag-3bf34-61db4767441b.json:/keys/chatrag-3bf34-61db4767441b.json

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    ports:
      - "5432:5432"
    volumes:
      - langflow-postgres:/var/lib/postgresql/data

volumes:
  langflow-postgres:
  langflow-data:
