version: '3.8'

services:
  langflow:
    build:
      context: .
      dockerfile: docker_example/Dockerfile
    restart: always
    depends_on:
      - postgres
    environment:
      LANGFLOW_DATABASE_URL: postgresql://langflow:langflow@postgres:5432/langflow
      LANGFLOW_CONFIG_DIR: app/langflow
      LANGFLOW_HOST: 0.0.0.0
      LANGFLOW_PORT: 7860
    volumes:
      - langflow-data:/app/langflow
    ports:
      - "7860:7860"

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    ports:
      - "5432:5432"
    volumes:
      - langflow-postgres:/var/lib/postgresql/data

volumes:
  langflow-postgres:
  langflow-data:
